#!/usr/bin/env python3
"""Campaign 25: the tick-1b token set, unchanged, against Cosmic only.

Closes ticks 1b/2 against Cosmic. The exact protocol requested:
  token -> {raw, sha256hex} x EVP-{MD5, SHA256} x cosmic (salt 2d3f6fe06dc950e6, ct 1328 B)
Hit rule: strict PKCS#7 AND (pad>=4 or >=4-byte magic or printable structure).
Non-hit: pad 1-3 with garbage, printable fragments.

Token set = every distinct raw candidate string generated by campaign_24_board.py (tick 1b,
both boards; the boards share coordinates, so the union is one set). Written to
../attempts/campaign_25_tokens.txt so the list is explicit.
"""
import os, sys, hashlib, importlib.util
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from aes_try import Harness, ATT

spec = importlib.util.spec_from_file_location("c24", os.path.join(HERE, "campaign_24_board.py"))
c24 = importlib.util.module_from_spec(spec); spec.loader.exec_module(c24)

def tokens():
    out = []
    seen = set()
    def add(s, tag):
        if s not in seen:
            seen.add(s); out.append((s, tag))
    words = {"KING": "KING", "QUEEN": "QUEEN", "C": "C",
             "KINGQUEENC": "KINGQUEENC", "QUEENKINGC": "QUEENKINGC"}
    for bn, board in c24.BOARDS.items():
        for wn, w in words.items():
            cs = c24.coords(board, w)
            for sn, sv in c24.serials(cs).items():
                add(sv, f"{bn}:rm:{wn}:{sn}")
            add(w.upper(), f"{bn}:rm:{wn}:ctrl")
        for row_assign in ((0, 1), (1, 0)):
            d0, d1 = [], []
            for i, ch in enumerate(board):
                r, c = i // 14, i % 14
                d0.append(f"{row_assign[r]}{c}"); d1.append(f"{row_assign[r]}{c+1}")
            for tag, seq in (("cb0", "".join(d0)), ("cb1", "".join(d1))):
                add(seq, f"{bn}:cb:{row_assign}:{tag}")
                s2 = seq if len(seq) % 2 == 0 else seq + "0"
                add(bytes(int(s2[k:k+2]) for k in range(0, len(s2), 2)).hex(), f"{bn}:cb:{row_assign}:{tag}:nib")
    return out

def main():
    toks = tokens()
    with open(os.path.join(ATT, "campaign_25_tokens.txt"), "w") as f:
        for s, tag in toks:
            f.write(f"{tag}\t{s}\n")
    h = Harness("campaign_25_cosmic_tick1b")
    for s, tag in toks:
        h.try_pw(s, f"c25:{tag}:raw", targets=["cosmic"], kdfs=["m5", "s2"])
        h.try_pw(hashlib.sha256(s.encode()).hexdigest(), f"c25:{tag}:sha256hex", targets=["cosmic"], kdfs=["m5", "s2"])
    print("tokens:", len(toks))
    h.finish("campaign_25_cosmic_tick1b")
    # near-miss dump (pad-valid but non-hit) for the record
    print("pad-valid non-hits logged:", sum(1 for _ in open(h.log_path)))

if __name__ == "__main__":
    main()
